### ISSUE TITLE
validation of native_language for bilinguals

### ISSUE THREAD

**Issue by kachergis** [langcog/peekds#33]
according to the column definition of native_language* it is possible to input multiple ISO language codes separated by a comma, but the validator does not accept it. Error:
"\n\t-\tThe native languages of subjects  eng,fre  do not belong in the allowed language list in json. Please see function list_language_choices()."

* "participants' native language (in ISO 6390-2); potentially a string of multiple language codes separated by a ", " (in the case of bilinguals)"

**Comment by kachergis** [comment]
list_language_choices() includes "multiple": should we just use that? (and if not, maybe it should not be an option?)

**Comment by lingerxu** [comment]
This should pass the validator, we are allowing multiple language (in ISO 6390-2) input separated by "," or " ". What's the dataset? I am gonna check in on this.

**Comment by kachergis** [comment]
"fre, eng" / "fra, eng" / "eng, fra" do not work ("byers-heinlein_2017")

**Comment by kachergis** [comment]
nor "eng fre"

**Comment by lingerxu** [comment]
Update the version of peekds. I just tested the above fields, the all work with the current validator. If language codes are not ISO 6390-2 (e.g. bork), the error message should point out which row instead of the list of languages: The subjects' native languages in the following entry row(s) 31 do not belong in the allowed language list in json. Please see function list_language_choices()."
