### ISSUE TITLE
need storage space for the raw+processed EtDS

### ISSUE THREAD

**Issue by lingerxu** [langcog/peekds#7]

**Comment by smeylan** [comment]
I can offer to keep these on my big workstation (Chompsky), as we did with childes-db. What we found for that project was that it was better to keep it on a machine that isn't on EC2 so that the EC2 contents can always be regenerated. Mika and I can then push to the EC2 (mysql) or S3 (sqldumps) or whatever

**Comment by mcfrank** [comment]
That sounds like a reasonable solution. Do we want to have a dropbox mirror
too or something?
